# Generated by Django 6.1 on 2026-08-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='lease_agreements/'),
        ),
        migrations.AddField(
            model_name='lease',
            name='expiry_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='reminder_30_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='reminder_3_months_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lease',
            name='reminder_7_days_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
    ]
