# Generated by Django 6.1 on 2026-08-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_lease_agreement_file_lease_expiry_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='expiry_notification_sent',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='reminder_30_days_sent',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='reminder_3_months_sent',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='reminder_7_days_sent',
        ),
        migrations.CreateModel(
            name='LeaseReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='properties.lease')),
            ],
            options={
                'ordering': ['-days_before'],
                'constraints': [models.UniqueConstraint(fields=('lease', 'days_before'), name='unique_lease_reminder_days')],
            },
        ),
    ]
