# Generated by Django 6.1 on 2026-08-31 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_tenant_email_tenant_first_name_tenant_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('gstin', models.CharField(blank=True, default='', max_length=30)),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('account_number', models.CharField(blank=True, default='', max_length=100)),
                ('ifsc', models.CharField(blank=True, default='', max_length=20)),
                ('branch', models.CharField(blank=True, default='', max_length=150)),
                ('payment_instructions', models.TextField(blank=True, default='')),
                ('logo', models.FileField(blank=True, null=True, upload_to='invoice_assets/logos/')),
                ('signature', models.FileField(blank=True, null=True, upload_to='invoice_assets/signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='properties.landlord')),
            ],
        ),
    ]
