# Generated by Django 6.1 on 2026-09-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_invoicesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gst_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='shop_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
