# Generated by Django 6.1 on 2026-09-02 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_tenant_gst_number_tenant_gst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesettings',
            name='building',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_settings', to='properties.building'),
        ),
        migrations.AddField(
            model_name='invoicesettings',
            name='due_day',
            field=models.PositiveSmallIntegerField(default=7, help_text='Day of month (1-31) when the invoice is due.'),
        ),
        migrations.AlterField(
            model_name='invoicesettings',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_invoice_settings', to='properties.landlord'),
        ),
    ]
