# Generated by Django 6.1 on 2026-09-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_invoicesettings_upi_id_invoicesettings_upi_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingemaillog',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='properties.lease'),
        ),
        migrations.AlterField(
            model_name='billingemaillog',
            name='email_type',
            field=models.CharField(choices=[('invoice', 'Commercial Invoice'), ('receipt', 'Payment Receipt'), ('reminder', 'Payment Reminder'), ('lease_renewal', 'Lease Renewal Notice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='billingemaillog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='properties.payment'),
        ),
    ]
