# Generated by Django 6.1 on 2026-09-23 15:25

import django.db.models.deletion
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_billingemaillog_lease_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('security', 'Security'), ('structural', 'Structural'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='landlord_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to='properties.landlord'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='Designates whether the tenant is required to set a new password on first login.'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.maintenance_image_upload_to),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='open', max_length=20),
        ),
    ]
