# Generated by Django 6.1 on 2026-09-23 16:16

import django.db.models.deletion
import properties.upi_service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_maintenancerequest_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='upi_id',
            field=models.CharField(blank=True, default='', help_text='Landlord UPI ID / VPA for receiving direct rent payments (e.g. name@upi)', max_length=100, validators=[properties.upi_service.validate_upi_id]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('upi', 'UPI'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Exact amount required for the payment', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_method', models.CharField(default='upi', max_length=20)),
                ('upi_id', models.CharField(blank=True, default='', help_text='Landlord UPI ID at the time of payment initiation', max_length=100)),
                ('transaction_reference', models.CharField(db_index=True, help_text='Unique internal reference for this UPI transaction', max_length=100, unique=True)),
                ('utr', models.CharField(blank=True, default='', help_text='Bank / UPI reference number (UTR) provided by the tenant', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='properties.building')),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='properties.landlord')),
                ('payment', models.ForeignKey(help_text='Associated rent/invoice billing record', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='properties.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='properties.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='properties__status_c4c84c_idx'), models.Index(fields=['transaction_reference'], name='properties__transac_f39193_idx'), models.Index(fields=['payment', 'status'], name='properties__payment_758c9b_idx')],
            },
        ),
    ]
