# Generated by Django 6.1 on 2026-09-23 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_landlord_upi_id_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='landlord_avatars/'),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_payment_received', models.BooleanField(default=True, help_text="Get notified when a tenant's rent payment is successfully recorded.")),
                ('rent_payment_pending', models.BooleanField(default=True, help_text='Get notified when a rent payment requires verification.')),
                ('rent_overdue', models.BooleanField(default=True, help_text="Get notified when a tenant's rent becomes overdue.")),
                ('maintenance_requests', models.BooleanField(default=True, help_text='Get notified when a tenant submits a maintenance request.')),
                ('lease_expiry', models.BooleanField(default=True, help_text='Get notified when a lease is approaching its expiry date.')),
                ('new_tenant', models.BooleanField(default=True, help_text='Get notified when a new tenant is added.')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='Preferred UI appearance theme.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='properties.landlord')),
            ],
        ),
    ]
